// Temporary mock data — used while backend is not connected yet
export const mockDrugs = [
  {
    id: 1,
    drug_name: 'Paracetamol',
    generic_name: 'Acetaminophen',
    brand_names: 'Panadol, Tylenol, Adol',
    drug_class: 'Analgesic / Antipyretic',
    drug_form: 'Tablet',
    strength: '500 mg',
    pregnancy_category: 'B',
    rx_otc: 'OTC',
    indications: 'Relief of mild to moderate pain and fever.',
    side_effects: 'Nausea, rash (rare). Overdose can cause liver damage.',
    warnings: 'Do not exceed 4g/day. Avoid in liver disease.',
    alcohol_interaction: false,
    hypertension_risk: false,
  },
  {
    id: 2,
    drug_name: 'Ibuprofen',
    generic_name: 'Ibuprofen',
    brand_names: 'Advil, Brufen, Nurofen',
    drug_class: 'NSAID',
    drug_form: 'Tablet',
    strength: '400 mg',
    pregnancy_category: 'D',
    rx_otc: 'OTC',
    indications: 'Pain, inflammation, fever.',
    side_effects: 'Stomach upset, ulcers with long-term use.',
    warnings: 'Avoid in third trimester of pregnancy.',
    alcohol_interaction: true,
    hypertension_risk: true,
  },
  {
    id: 3,
    drug_name: 'Amoxicillin',
    generic_name: 'Amoxicillin',
    brand_names: 'Augmentin, Amoxil',
    drug_class: 'Antibiotic (Penicillin)',
    drug_form: 'Capsule',
    strength: '500 mg',
    pregnancy_category: 'B',
    rx_otc: 'Rx',
    indications: 'Bacterial infections — throat, ear, urinary tract.',
    side_effects: 'Diarrhea, rash, allergic reaction.',
    warnings: 'Check for penicillin allergy before use.',
    alcohol_interaction: false,
    hypertension_risk: false,
  },
  {
    id: 4,
    drug_name: 'Metformin',
    generic_name: 'Metformin HCl',
    brand_names: 'Glucophage, Glycon',
    drug_class: 'Antidiabetic (Biguanide)',
    drug_form: 'Tablet',
    strength: '500 mg / 850 mg / 1000 mg',
    pregnancy_category: 'B',
    rx_otc: 'Rx',
    indications: 'Type 2 diabetes management.',
    side_effects: 'Nausea, diarrhea, stomach upset.',
    warnings: 'Avoid in kidney disease. Hold before contrast imaging.',
    alcohol_interaction: true,
    hypertension_risk: false,
  },
  {
    id: 5,
    drug_name: 'Amlodipine',
    generic_name: 'Amlodipine Besylate',
    brand_names: 'Norvasc, Amlovas',
    drug_class: 'Calcium Channel Blocker',
    drug_form: 'Tablet',
    strength: '5 mg / 10 mg',
    pregnancy_category: 'C',
    rx_otc: 'Rx',
    indications: 'Hypertension, angina.',
    side_effects: 'Ankle swelling, flushing, headache.',
    warnings: 'Monitor blood pressure regularly.',
    alcohol_interaction: true,
    hypertension_risk: false,
  },
  {
    id: 6,
    drug_name: 'Warfarin',
    generic_name: 'Warfarin Sodium',
    brand_names: 'Coumadin, Jantoven',
    drug_class: 'Anticoagulant',
    drug_form: 'Tablet',
    strength: '1 mg / 2 mg / 5 mg',
    pregnancy_category: 'X',
    rx_otc: 'Rx',
    indications: 'Prevention of blood clots, atrial fibrillation.',
    side_effects: 'Bleeding, bruising.',
    warnings: 'Many food and drug interactions. Regular INR monitoring required.',
    alcohol_interaction: true,
    hypertension_risk: false,
  },
]

export const mockHerbs = [
  {
    id: 1,
    herb_name: 'Ginger',
    scientific_name: 'Zingiber officinale',
    common_names: 'Ginger root, Adrak',
    family: 'Zingiberaceae',
    parts_used: 'Root / Rhizome',
    benefits: 'Anti-nausea, anti-inflammatory, digestive aid, relieves morning sickness.',
    uses: 'Nausea, vomiting, indigestion, arthritis pain, cold and flu.',
    side_effects: 'Heartburn in high doses.',
    pregnancy_safe: true,
    hypertension_risk: false,
    origin_region: 'South Asia',
  },
  {
    id: 2,
    herb_name: 'Garlic',
    scientific_name: 'Allium sativum',
    common_names: 'Garlic, Thoom',
    family: 'Amaryllidaceae',
    parts_used: 'Bulb / Cloves',
    benefits: 'Lowers blood pressure, antimicrobial, cholesterol reduction.',
    uses: 'Hypertension, high cholesterol, infections.',
    side_effects: 'Bad breath, stomach upset. Increases bleeding risk.',
    pregnancy_safe: true,
    hypertension_risk: false,
    origin_region: 'Central Asia',
  },
  {
    id: 3,
    herb_name: 'St. John\'s Wort',
    scientific_name: 'Hypericum perforatum',
    common_names: 'St. John\'s Wort, Tipton\'s weed',
    family: 'Hypericaceae',
    parts_used: 'Flowering tops',
    benefits: 'Mild to moderate depression, anxiety, wound healing.',
    uses: 'Depression, nerve pain, seasonal affective disorder.',
    side_effects: 'Photosensitivity, interferes with many medications.',
    pregnancy_safe: false,
    hypertension_risk: false,
    origin_region: 'Europe',
  },
  {
    id: 4,
    herb_name: 'Chamomile',
    scientific_name: 'Matricaria chamomilla',
    common_names: 'Chamomile, Babunah',
    family: 'Asteraceae',
    parts_used: 'Flowers',
    benefits: 'Calming, anti-anxiety, anti-inflammatory, promotes sleep.',
    uses: 'Insomnia, anxiety, stomach cramps, skin inflammation.',
    side_effects: 'Allergic reaction in people sensitive to ragweed.',
    pregnancy_safe: null,
    hypertension_risk: false,
    origin_region: 'Europe, North Africa',
  },
  {
    id: 5,
    herb_name: 'Turmeric',
    scientific_name: 'Curcuma longa',
    common_names: 'Turmeric, Kurkum',
    family: 'Zingiberaceae',
    parts_used: 'Rhizome / Root',
    benefits: 'Powerful anti-inflammatory (curcumin), antioxidant, liver support.',
    uses: 'Arthritis, liver disease, skin conditions, digestive issues.',
    side_effects: 'High doses may cause stomach upset or increase bleeding.',
    pregnancy_safe: true,
    hypertension_risk: false,
    origin_region: 'South Asia',
  },
  {
    id: 6,
    herb_name: 'Black Seed',
    scientific_name: 'Nigella sativa',
    common_names: 'Black Seed, Habbatus Sauda, Nigella',
    family: 'Ranunculaceae',
    parts_used: 'Seeds / Oil',
    benefits: 'Immune booster, anti-inflammatory, antidiabetic, antimicrobial.',
    uses: 'Asthma, diabetes, high blood pressure, immunity.',
    side_effects: 'May lower blood pressure and blood sugar significantly.',
    pregnancy_safe: false,
    hypertension_risk: true,
    origin_region: 'Middle East, South Asia',
  },
]

export const mockInteractions = [
  { id: 1, drug_name: 'Warfarin', herb_name: 'Garlic', severity: 'high',
    description: 'Garlic may increase the blood-thinning effect of Warfarin, raising bleeding risk.' },
  { id: 2, drug_name: 'Warfarin', herb_name: 'St. John\'s Wort', severity: 'contraindicated',
    description: 'St. John\'s Wort significantly reduces Warfarin levels, increasing clot risk.' },
  { id: 3, drug_name: 'Metformin', herb_name: 'Black Seed', severity: 'moderate',
    description: 'Black Seed may enhance blood sugar lowering; monitor glucose carefully.' },
]
